[window]
decorations = "None"
opacity = 0.8

[window.padding]
x = 10
y = 10

[font]
normal = {family = "JetBrains Mono", style = "Medium"}
size = 12

[colors.primary]
background = "#282828"
foreground = "#f9f5d7"

[colors.normal]
black = "#282828"
red = "#cc241d"
green = "#83a598"
yellow = "#fabd2f"
blue = "#98971a"
magenta = "#d3869b"
cyan = "#b8bb26"
white = "#fbf1c7"
